In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier   
from sklearn.model_selection import train_test_split,GridSearchCV,KFold
from sklearn import metrics
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,classification_report
from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier

# **Importing the dataset** 

In [2]:

df = pd.DataFrame(load_breast_cancer()['data'],columns=load_breast_cancer()['feature_names'])
df['y'] = load_breast_cancer()['target']

# **Data Preprocessing**

In [3]:
df.head()

mean radius  mean texture  ...  worst fractal dimension  y
0        17.99         10.38  ...                  0.11890  0
1        20.57         17.77  ...                  0.08902  0
2        19.69         21.25  ...                  0.08758  0
3        11.42         20.38  ...                  0.17300  0
4        20.29         14.34  ...                  0.07678  0

[5 rows x 31 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [5]:
df.describe()

mean radius  mean texture  ...  worst fractal dimension           y
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

### Spliting the data into training and testing data

In [6]:
#Seperating the features from the label
features=df.drop(columns=['y'],axis=1)
feature_list=list(features.columns)
X=df[feature_list]
y=df['y']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

# 3 .) Implementation of the Classification Models 

## a.) Decision Tree Classifier

In [7]:
#Building a Decision Tree Classifier object
DesTreeClf=DecisionTreeClassifier()

#Fitting the Decision Tree Model
dtModel=DesTreeClf.fit(X_train,y_train)

#Let us make some predictions to understand the accuracies of the training and testing predictions

y_train_pred=dtModel.predict(X_train)
y_test_pred=dtModel.predict(X_test)

print('The accuracy of the training model:',accuracy_score(y_train,y_train_pred)) 
print('The accuracy of the testing model:',accuracy_score(y_test,y_test_pred)) 


The accuracy of the training model: 1.0
The accuracy of the testing model: 0.9473684210526315


## b.) Random Forest Classifier

In [8]:
estimator=RandomForestClassifier(random_state=0, warm_start=True)
tuned_parameters={'max_depth':[10,20],'n_estimators':[50],'min_samples_leaf':[10]}
cv_grid=GridSearchCV(estimator,param_grid=tuned_parameters,scoring='roc_auc',verbose=5)
cv_grid=cv_grid.fit(X_train,y_train)
cv_grid

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.977, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.988, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.995, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.991, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.4s remaining:    0.0s


[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.992, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.977, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.988, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.995, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.991, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.992, total=   0.1s


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.9s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=0,
                                

In [9]:
cv_grid.cv_results_

{'mean_fit_time': array([0.08671951, 0.08430572]),
 'mean_score_time': array([0.00726128, 0.00619059]),
 'mean_test_score': array([0.98859649, 0.98859649]),
 'param_max_depth': masked_array(data=[10, 20],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[10, 10],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_n_estimators': masked_array(data=[50, 50],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 10, 'min_samples_leaf': 10, 'n_estimators': 50},
  {'max_depth': 20, 'min_samples_leaf': 10, 'n_estimators': 50}],
 'rank_test_score': array([1, 1], dtype=int32),
 'split0_test_score': array([0.97678019, 0.97678019]),
 'split1_test_score': array([0.98813209, 0.98813209]),
 'split2_test_score': array([0.99484004, 0.99484004]),
 'split3_test_score': array([0.99122807, 0.99122807]),
 'split4_test_score

In [10]:
#Predictions using the accuracies
y_train_pred_rf=cv_grid.predict(X_train)
y_test_pred_rf=cv_grid.predict(X_test)

print('Accuracy of the Random Forest model on the training data:',accuracy_score(y_train,y_train_pred_rf))
print('Accuracy of the Random Forest model on the testing data:',accuracy_score(y_test,y_test_pred_rf))

print('Precision of the Random Forest model on the training data:',precision_score(y_train,y_train_pred_rf))
print('Precision of the Random Forest model on the testing data:',precision_score(y_test,y_test_pred_rf))

print('The confusion matrix for the training data:')
confusion_matrix(y_train,y_train_pred_rf)
print('The confusion matrix for the testing data:')
confusion_matrix(y_test,y_test_pred_rf)

Accuracy of the Random Forest model on the training data: 0.9736263736263736
Accuracy of the Random Forest model on the testing data: 0.9473684210526315
Precision of the Random Forest model on the training data: 0.9789473684210527
Precision of the Random Forest model on the testing data: 0.9342105263157895
The confusion matrix for the training data:
The confusion matrix for the testing data:


array([[37,  5],
       [ 1, 71]])

## c.) Gradient Boosting Method

In [11]:
gb=GradientBoostingClassifier(learning_rate=0.1)
gb.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'deviance',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'presort': 'deprecated',
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [12]:
gbModel=gb.fit(X_train,y_train)

In [13]:
y_train_pred_gb=gbModel.predict(X_train)
y_test_pred_gb=gbModel.predict(X_test)

print('The Classification report of the Gradient Boosting model is as follows:')
print(classification_report(y_test,y_test_pred_gb))

The Classification report of the Gradient Boosting model is as follows:
              precision    recall  f1-score   support

           0       1.00      0.90      0.95        42
           1       0.95      1.00      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.95      0.96       114
weighted avg       0.97      0.96      0.96       114



In [14]:
print('Confusion Matrix:')
print(confusion_matrix(y_test,y_test_pred_gb))

Confusion Matrix:
[[38  4]
 [ 0 72]]


## d.) KNN Classification 

In [15]:
#Building a KNN classifier object
knn=KNeighborsClassifier()

#Fitting a prediction model based on KNN
knnModel=knn.fit(X_train,y_train)

#Predicting values using the 
y_train_pred_knn=knnModel.predict(X_train)
y_test_pred_knn=knnModel.predict(X_test)

print('Classification Report for the KNN Model:')
print(classification_report(y_test,y_test_pred_knn))

Classification Report for the KNN Model:
              precision    recall  f1-score   support

           0       0.95      0.88      0.91        42
           1       0.93      0.97      0.95        72

    accuracy                           0.94       114
   macro avg       0.94      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114



In [16]:
print('Confusion Matrix for KNN Model:')
print(confusion_matrix(y_test,y_test_pred_knn))

Confusion Matrix for KNN Model:
[[37  5]
 [ 2 70]]


# **4.) Tuning the hyper-parameters of the Decision Tree model**

In [17]:
tuning_parameters={'criterion': ['gini', 'entropy'], 'max_depth': [10, 20, 50, 100], 'min_samples_leaf': [10, 20, 50]}
estimatorDT=DecisionTreeClassifier()

In [18]:
cv_gridDT=GridSearchCV(estimator=estimatorDT,param_grid=tuning_parameters,scoring='roc_auc',verbose=5)
dtModelWPT=cv_grid.fit(X_train,y_train)
dtModelWPT.cv_results_

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.977, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.988, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.995, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.3s remaining:    0.0s


[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.991, total=   0.1s
[CV] max_depth=10, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=10, min_samples_leaf=10, n_estimators=50, score=0.992, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.977, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.4s remaining:    0.0s


[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.988, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.995, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.991, total=   0.1s
[CV] max_depth=20, min_samples_leaf=10, n_estimators=50 ..............
[CV]  max_depth=20, min_samples_leaf=10, n_estimators=50, score=0.992, total=   0.1s


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    1.0s finished


{'mean_fit_time': array([0.09522319, 0.08938818]),
 'mean_score_time': array([0.00919666, 0.00887032]),
 'mean_test_score': array([0.98859649, 0.98859649]),
 'param_max_depth': masked_array(data=[10, 20],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[10, 10],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_n_estimators': masked_array(data=[50, 50],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 10, 'min_samples_leaf': 10, 'n_estimators': 50},
  {'max_depth': 20, 'min_samples_leaf': 10, 'n_estimators': 50}],
 'rank_test_score': array([1, 1], dtype=int32),
 'split0_test_score': array([0.97678019, 0.97678019]),
 'split1_test_score': array([0.98813209, 0.98813209]),
 'split2_test_score': array([0.99484004, 0.99484004]),
 'split3_test_score': array([0.99122807, 0.99122807]),
 'split4_test_score

In [19]:
y_test_pred_dtpt=dtModelWPT.predict(X_test)
print('Classification Report for the decision tree model with tuned parameters:')
print(classification_report(y_test,y_test_pred_dtpt))

Classification Report for the decision tree model with tuned parameters:
              precision    recall  f1-score   support

           0       0.97      0.88      0.93        42
           1       0.93      0.99      0.96        72

    accuracy                           0.95       114
   macro avg       0.95      0.93      0.94       114
weighted avg       0.95      0.95      0.95       114



In [20]:
print('Confusion Matrix for the Decision Tree Model with Parameter Tuning:')
print(confusion_matrix(y_test,y_test_pred_dtpt))

Confusion Matrix for the Decision Tree Model with Parameter Tuning:
[[37  5]
 [ 1 71]]


# **5.) Comparision of Models**

**The model with Gradient Boosting Method has the highest accuracy and a better confusion matrix than that of any other model and thus it is the best model**